---
name: Lint

on:
  push:
    branches:
      - master
  pull_request: {branches: main}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: {node-version: 13.x}
      - run: |
        yarn
        yarn global add eslint
        yarn lint:check
        yarn prettier:check
        yarn alex
      # yarn test